# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NoName', max_length=150)),
                ('slug', models.SlugField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='../media/images/')),
            ],
            options={
                'verbose_name': 'Partie du site',
                'verbose_name_plural': 'Parties du site',
            },
        ),
    ]
