# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text_field', models.CharField(default='NoName', max_length=150)),
                ('maj_date', models.DateTimeField()),
                ('slug', models.CharField(default='fKlhSd', max_length=6, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='../media/images/')),
                ('fiche', models.TextField(default='No Fiche Yet')),
                ('private', models.BooleanField(default=True)),
            ],
        ),
    ]
