# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': "Page d'information", 'verbose_name_plural': "Pages d'information"},
        ),
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.CharField(default='BPjxus', max_length=6, unique=True),
        ),
    ]
