# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0002_auto_20170725_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='name_text_field',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.CharField(default='NxyDRi', max_length=6, unique=True),
        ),
    ]
