# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infopage', '0003_auto_20170725_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='slug',
            field=models.CharField(default='6DeyQj', max_length=6, unique=True),
        ),
    ]
