# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text_field', models.CharField(default='NoName', max_length=150)),
                ('maj_date', models.DateTimeField()),
                ('picture', models.ImageField(default='/home/meliodas/Documents/DUT/conf/kairos/prog/ico_kairos.png', upload_to='')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='types',
            field=models.ManyToManyField(to='project_review.Type'),
        ),
    ]
