# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_review', '0002_auto_20170718_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='/home/meliodas/Documents/DUT/conf/kairos/prog/ico_kairos.png', upload_to='../media/images/'),
        ),
    ]
